### ISSUE TITLE
Fix PyPi homepage link

### ISSUE THREAD

**Issue by abdullahdevrel** [rennf93/fastapi-guard#8]
The PyPi project page does not have the accurate URL for the repo: https://pypi.org/project/fastapi-guard/

![image](https://github.com/user-attachments/assets/db7f0d52-c20d-479e-9400-b0e5725ea8ed)

```diff
++ https://github.com/rennf93/fastapi-guard
-- https://github.com/rennf93/fastapi_guard
```

**Comment by rennf93** [comment]
Fixed and will be included on the next release.

Thank you for taking the time ❤️ I really appreciate it!

**Comment by rennf93** [comment]
Closing this issue now. -
